name: norminette

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  norminette:
    runs-on: ubuntu-latest
    name: 42 Norminette v3
    steps:
      - uses: actions/checkout@v2
      - uses: alexandregv/norminette-action@v3
            
