name: norminette

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  norminette:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: 42 Norminette v3
        uses: alexandregv/norminette-action@v3
